import { afterEach, beforeEach, describe, expect, test } from "bun:test";
import { mkdirSync, mkdtempSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { defaultContext } from "../src/adapters.js";
import { CTX_DIR } from "../src/core.js";

function freshDir(prefix: string): string {
  return mkdtempSync(join(tmpdir(), prefix));
}

describe("adapters.defaultContext runtime guard (issue #92)", () => {
  let base: string;

  beforeEach(() => {
    base = freshDir("vf-92-");
  });

  afterEach(() => {
    rmSync(base, { recursive: true, force: true });
  });

  test("without base: returns permissive placeholder (preserves init-flow seeding)", () => {
    const ctx = defaultContext();
    expect(ctx.name).toBeTruthy();
    expect(ctx.goal).toContain("Describe the task in");
    expect(ctx.summary).toContain("Project context is generated by VibeFlow");
  });

  test("with base and init not run: throws with a clear message", () => {
    // No .vibeflow/WORKFLOW_STATE.json in `base` — init was never run.
    expect(() => defaultContext({ base })).toThrow(/vf init/i);
  });

  test("with base and init not run: error names the missing state file", () => {
    expect(() => defaultContext({ base })).toThrow(/WORKFLOW_STATE\.json/);
  });

  test("with base after init: returns context seeded from cwd basename (placeholder values, not thrown)", () => {
    // Simulate a completed init by writing a minimal WORKFLOW_STATE.json.
    mkdirSync(join(base, CTX_DIR), { recursive: true });
    writeFileSync(
      join(base, CTX_DIR, "WORKFLOW_STATE.json"),
      JSON.stringify({ task_id: "TASK-1" }),
    );
    const ctx = defaultContext({ base });
    expect(ctx.name).toBeTruthy();
    // The default name is derived from cwd() (per existing behavior); it must be
    // a non-empty string when init has been recorded.
    expect(typeof ctx.name).toBe("string");
    expect(ctx.name.length).toBeGreaterThan(0);
  });

  test("with base whose state file is empty / missing still throws (not silently returns placeholder)", () => {
    // Sanity: even an empty dir under .vibeflow/ without the state file throws.
    mkdirSync(join(base, CTX_DIR), { recursive: true });
    expect(() => defaultContext({ base })).toThrow(/vf init/i);
  });
});
