import { describe, expect, test } from "bun:test";
import { mkdtempSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import type { WorkUnit, WorkflowState } from "../src/core.js";
import { writeState } from "../src/core.js";
import {
  applyDelete,
  deleteUnit,
  importWorkflow,
  isManagedGenerated,
  mergeStates,
  planDelete,
} from "../src/workflow/lifecycle.js";

function tmp(): string {
  return mkdtempSync(join(tmpdir(), "vf-lifecycle-"));
}

function unit(name: string, over: Partial<WorkUnit> = {}): WorkUnit {
  return {
    name,
    status: "done",
    confidence: 1,
    scope: ["src/core"],
    gates: { build: "pass", lint: "pass", test: "pass", review: "pass" },
    resources: { agents: 1, tokens: 100, cost_usd: 0.5, wall_seconds: 10 },
    evidence: ["src-repo/.viteflow/workunits/x/evidence/proof.json"],
    ...over,
  };
}

function state(over: Partial<WorkflowState> = {}): WorkflowState {
  return {
    task_id: "TASK-1",
    goal: "ship the parser",
    success_criteria: ["c1"],
    work_units: [],
    totals: { units: 0, done: 0, tokens: 0, cost_usd: 0, wall_seconds: 0 },
    ...over,
  };
}

describe("planDelete", () => {
  test("default scope targets only .viteflow and preserves engine files", () => {
    const dir = tmp();
    writeState(dir, state({ work_units: [unit("alpha"), unit("beta")] }));
    writeFileSync(join(dir, "CLAUDE.md"), "# CLAUDE.md\n\nGenerated by VibeFlow\n");
    writeFileSync(join(dir, "AGENTS.md"), "# AGENTS.md\n\nGenerated by VibeFlow\n");

    const plan = planDelete(dir);
    expect(plan.targets).toEqual([join(dir, ".viteflow")]);
    expect(plan.preserved).toContain(join(dir, "CLAUDE.md"));
    expect(plan.preserved).toContain(join(dir, "AGENTS.md"));
    expect(plan.summary).toContain("ship the parser");
    expect(plan.summary).toContain("alpha");
    expect(plan.summary).toContain("beta");
    rmSync(dir, { recursive: true, force: true });
  });

  test("--all targets managed engine files but preserves hand-edited ones", () => {
    const dir = tmp();
    writeState(dir, state());
    writeFileSync(join(dir, "CLAUDE.md"), "# CLAUDE.md\n\nThis file is generated by VibeFlow.\n");
    writeFileSync(join(dir, "AGENTS.md"), "# my own notes, hand-edited, no marker\n");

    const plan = planDelete(dir, { all: true });
    expect(plan.targets).toContain(join(dir, ".viteflow"));
    expect(plan.targets).toContain(join(dir, "CLAUDE.md"));
    expect(plan.preserved).toContain(join(dir, "AGENTS.md"));
    expect(plan.targets).not.toContain(join(dir, "AGENTS.md"));
    expect(plan.summary).toContain("AGENTS.md");
    rmSync(dir, { recursive: true, force: true });
  });

  test("no .viteflow yields empty targets and a clear summary", () => {
    const dir = tmp();
    const plan = planDelete(dir);
    expect(plan.targets).toEqual([]);
    expect(plan.preserved).toEqual([]);
    expect(plan.summary).toContain("no workflow");
    expect(plan.summary).toContain(dir);
    rmSync(dir, { recursive: true, force: true });
  });
});

describe("applyDelete", () => {
  test("removes exactly plan.targets and never .git", () => {
    const dir = tmp();
    const calls: string[] = [];
    const plan = {
      repo: dir,
      ctxDir: join(dir, ".viteflow"),
      targets: [join(dir, ".viteflow"), join(dir, ".git")],
      preserved: [],
      summary: "",
    };
    const removed = applyDelete(plan, (p) => {
      calls.push(p);
    });
    expect(calls).toEqual([join(dir, ".viteflow")]);
    expect(removed).toEqual([join(dir, ".viteflow")]);
    expect(calls).not.toContain(join(dir, ".git"));
    rmSync(dir, { recursive: true, force: true });
  });
});

describe("deleteUnit", () => {
  test("removes a named unit, recomputes totals, persists", () => {
    const dir = tmp();
    writeState(dir, state({ work_units: [unit("a"), unit("b")] }));
    const after = deleteUnit(dir, "a");
    expect(after).not.toBeNull();
    expect(after?.work_units.map((u) => u.name)).toEqual(["b"]);
    expect(after?.totals.units).toBe(1);
    rmSync(dir, { recursive: true, force: true });
  });

  test("returns null for an unknown unit name", () => {
    const dir = tmp();
    writeState(dir, state({ work_units: [unit("a")] }));
    expect(deleteUnit(dir, "ghost")).toBeNull();
    rmSync(dir, { recursive: true, force: true });
  });
});

describe("mergeStates", () => {
  test("renames collisions, resets imports, surfaces scope overlap, reconciles goals", () => {
    const dest = state({
      goal: "dest goal",
      success_criteria: ["c1"],
      work_units: [unit("shared", { scope: ["src/a"] })],
    });
    const src = state({
      goal: "src goal",
      success_criteria: ["c1", "c2"],
      work_units: [
        unit("shared", { scope: ["src/a"] }),
        unit("fresh", { scope: ["src/a"], status: "done", confidence: 1 }),
      ],
    });

    const res = mergeStates(dest, src, { onNameCollision: "rename", srcLabel: "lib" });

    expect(res.renamed).toContainEqual(["shared", "shared:lib"]);
    const imported = res.merged.work_units.find((u) => u.name === "shared:lib");
    expect(imported?.status).toBe("pending");
    expect(imported?.confidence).toBe(0);
    expect(imported?.evidence).toEqual([]);
    expect(res.conflicts.some((c) => c.kind === "scope-overlap")).toBe(true);
    expect(res.merged.success_criteria).toEqual(["c1", "c2", "src goal"]);
    expect(res.merged.goal).toBe("dest goal");
    expect(res.merged.totals.units).toBe(res.merged.work_units.length);
  });

  test("skip keeps dest, replace takes src", () => {
    const dest = state({ work_units: [unit("u", { confidence: 1, status: "done" })] });
    const src = state({ work_units: [unit("u")] });
    const skipped = mergeStates(dest, src, { onNameCollision: "skip", srcLabel: "lib" });
    expect(skipped.merged.work_units).toHaveLength(1);
    expect(skipped.merged.work_units[0]?.status).toBe("done");
    const replaced = mergeStates(dest, src, { onNameCollision: "replace", srcLabel: "lib" });
    expect(replaced.merged.work_units[0]?.status).toBe("pending");
    expect(replaced.added).toContain("u");
  });
});

describe("importWorkflow", () => {
  test("returns null when the source workflow is missing", () => {
    const dir = tmp();
    writeState(dir, state());
    const res = importWorkflow(dir, join(dir, "no-such-repo"), { onNameCollision: "rename" });
    expect(res).toBeNull();
    rmSync(dir, { recursive: true, force: true });
  });

  test("merges a real source workflow without writing", () => {
    const dest = tmp();
    const srcRepo = tmp();
    writeState(dest, state({ work_units: [unit("a")] }));
    writeState(srcRepo, state({ goal: "imported goal", work_units: [unit("b")] }));
    const res = importWorkflow(dest, srcRepo, { onNameCollision: "rename", srcLabel: "src" });
    expect(res?.added).toContain("b");
    expect(res?.merged.work_units.map((u) => u.name).sort()).toEqual(["a", "b"]);
    rmSync(dest, { recursive: true, force: true });
    rmSync(srcRepo, { recursive: true, force: true });
  });
});

describe("isManagedGenerated", () => {
  test("matches generated/managed markers, rejects hand-edited content", () => {
    expect(isManagedGenerated("This file is generated by VibeFlow.")).toBe(true);
    expect(isManagedGenerated("# Managed by VibeFlow (`vf tools`)")).toBe(true);
    expect(isManagedGenerated("# my own notes")).toBe(false);
  });
});
