import { describe, expect, test } from "bun:test";
import { VF_BLOCK_END, VF_BLOCK_START, mergeManagedBlock } from "../src/workflow/merge.js";

describe("mergeManagedBlock", () => {
  test("no existing file → fenced fresh block", () => {
    const r = mergeManagedBlock(null, "GENERATED BODY\ngenerated by VibeFlow");
    expect(r.mode).toBe("fresh");
    expect(r.backup).toBe(false);
    expect(r.content).toContain(VF_BLOCK_START);
    expect(r.content).toContain(VF_BLOCK_END);
    expect(r.content).toContain("GENERATED BODY");
  });

  test("existing fenced file → only the fenced region is swapped, human text kept", () => {
    const existing = `# My header I wrote\n\n${VF_BLOCK_START}\nOLD GENERATED\n${VF_BLOCK_END}\n\n## My footer notes\n`;
    const r = mergeManagedBlock(existing, "NEW GENERATED\ngenerated by VibeFlow");
    expect(r.mode).toBe("block-update");
    expect(r.backup).toBe(false);
    expect(r.content).toContain("# My header I wrote");
    expect(r.content).toContain("## My footer notes");
    expect(r.content).toContain("NEW GENERATED");
    expect(r.content).not.toContain("OLD GENERATED");
  });

  test("block-update is idempotent on repeated re-init", () => {
    const gen = "STABLE\ngenerated by VibeFlow";
    const once = mergeManagedBlock(null, gen).content;
    const twice = mergeManagedBlock(once, gen).content;
    const thrice = mergeManagedBlock(twice, gen).content;
    expect(thrice).toBe(twice);
  });

  test("legacy fully-VF file (marker, no fence) → replaced wholesale, no backup", () => {
    const existing = "# CLAUDE.md\n\nThis file is generated by VibeFlow.\n";
    const r = mergeManagedBlock(existing, "NEW\ngenerated by VibeFlow");
    expect(r.mode).toBe("replace-managed");
    expect(r.backup).toBe(false);
    expect(r.content).toContain(VF_BLOCK_START);
    expect(r.content).toContain("NEW");
  });

  test("hand-edited file (no fence, no marker) → human content kept, block appended, backup flagged", () => {
    const existing = "# my own notes, hand-written, precious\n";
    const r = mergeManagedBlock(existing, "GENERATED\ngenerated by VibeFlow");
    expect(r.mode).toBe("preserve-merge");
    expect(r.backup).toBe(true);
    expect(r.content).toContain("my own notes, hand-written, precious");
    expect(r.content).toContain(VF_BLOCK_START);
    expect(r.content).toContain("GENERATED");
  });
});
