import type { ProjectContext } from "../adapters/context-builders.js";
import {
  VF_BANNER,
  VF_COMMANDS,
  VF_WORKFLOW,
  aiGenerate,
  navigationPolicy,
} from "../adapters/context-builders.js";
import { CTX_DIR, type Engine, VERSION } from "../core.js";

function engineBody(engine: Engine, ctx: ProjectContext): string {
  const nav = navigationPolicy(ctx.settings);
  const navLine = nav ? `- ${nav}\n` : "";
  const goal = (ctx.goal ?? "").trim();
  const shared = `${VF_BANNER}Project: ${ctx.name}\nGoal: ${goal}\n\nPolicy:\n- Use verified skills when a task matches one; do not invent manual steps.\n- Back every factual claim with a file path, command output, or test result.\n- No verification, no completion.\n- Read curated guidance in ${CTX_DIR}/knowledge/ before knowledge-heavy tasks; keep it cross-referenced and current, never overwrite a human-curated source.\n- After acting, append a dated note to \`${CTX_DIR}/knowledge/log.md\` and keep \`${CTX_DIR}/knowledge/index.md\` current (append-only; never rewrite human-curated pages).\n- Author files incrementally: never write a large file in one operation (it times out) — create a small first part, then append/edit the rest in separate steps; when merging into an existing file, edit the specific section rather than rewriting the whole file.\n${navLine}\n${VF_COMMANDS}\n\n${VF_WORKFLOW}\n\n# Tool Error & Execution Policy\n- If any terminal command or test execution times out or returns an error code, do not give up immediately.\n- Autonomously analyze the error output or partial logs, fix the scripts or parameters, and retry the command up to 3 times.\n- Only prompt the user for feedback if the execution consistently fails after 3 distinct self-correction attempts.\n\nPowered by VibeFlow v${VERSION} — https://github.com/magicpro97/vibeflow\n`;
  if (engine === "claude") {
    return `# CLAUDE.md\n\n${shared}\nThe block between the \`vibeflow:start\`/\`vibeflow:end\` markers is generated by VibeFlow from ${CTX_DIR}/* and is replaced on \`vf init\`. Edit freely OUTSIDE the markers; that content is preserved across re-init.\n`;
  }
  return `# AGENTS.md\n\n${shared}\nThe block between the \`vibeflow:start\`/\`vibeflow:end\` markers is generated by VibeFlow from ${CTX_DIR}/* and is replaced on \`vf init\`. Edit freely OUTSIDE the markers; that content is preserved across re-init.\n`;
}

export function engineFiles(
  engine: Engine,
  ctx: ProjectContext,
  useAi = true,
): Record<string, string> {
  const compose = (prompt: string, fallback: () => string): string =>
    useAi ? aiGenerate(prompt, fallback) : fallback();
  const prompt = `Compose the ${engine} instruction file for project "${ctx.name}" from this context:\n${JSON.stringify(ctx)}`;
  const body = compose(prompt, () => engineBody(engine, ctx));
  switch (engine) {
    case "claude":
      return { "CLAUDE.md": body };
    case "codex":
      return { "AGENTS.md": body };
    case "copilot":
      return {
        "AGENTS.md": body,
        ".github/copilot-instructions.md": compose(
          `Compose .github/copilot-instructions.md for "${ctx.name}".`,
          () => `# Copilot Instructions\n\n${engineBody("copilot", ctx)}\n`,
        ),
      };
  }
}
