import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import type { WorkflowPhase } from "../ai-init-workflow.js";
import { CTX_DIR, VERSION } from "../core.js";
import { copyPhaseTemplateReferences, renderPhaseSkillToCanonical } from "./phase-canonical.js";
import { phaseSlug } from "./types.js";

// ── Phase skill template reader ──────────────────────────────────────────

/**
 * Read a phase template from the vibeflow package's `templates/skills/` directory.
 * Resolution: `new URL("../../templates/skills/...", import.meta.url)` resolves correct
 * path in both dev mode (src/workflow-artifacts/) and installed package (dist/ → ../templates/skills/).
 * Returns the raw template text, or null if not found.
 */
export function readPhaseSkillTemplate(phase: WorkflowPhase): string | null {
  const slug = phaseSlug(phase);
  const tmplUrl = new URL(`../../templates/skills/${slug}/SKILL.md`, import.meta.url);
  try {
    const path = tmplUrl.pathname;
    if (existsSync(path)) return readFileSync(path, "utf8");
  } catch {
    /* fallback: not found */
  }
  return null;
}

// ── Per-phase skill files (engine mirrors) ──────────────────────────────────
//
// Both canonical (`.vibeflow/skills/<phase>/`) and engine mirrors use the
// same `renderPhaseSkillToCanonical` body so they stay in lockstep.

export function renderPhaseSkill(phase: WorkflowPhase, projectName: string): string {
  return renderPhaseSkillToCanonical(phase, projectName, VERSION);
}

/**
 * Create `.vibeflow/context/` scaffolding with README placeholders.
 * Actual content is populated by `ai-init-context-updater` during AI enrichment.
 */

export function ensureContextDir(
  base: string,
  inject: { onWarn?: (msg: string) => void } = {},
): string[] {
  const onWarn = inject.onWarn ?? ((msg: string) => console.warn(msg));
  const written: string[] = [];

  const ctxDir = join(base, CTX_DIR, "context");
  mkdirSync(ctxDir, { recursive: true });

  const topics = [
    "modules",
    "conventions",
    "architecture",
    "database",
    "security",
    "api",
    "testing",
  ];

  const readmeContent = [
    "# Context by Topic",
    "",
    "This directory contains project context split by topic, so each phase only reads what it needs.",
    "",
    "| File | Content | Phases that need it |",
    "|------|---------|---------------------|",
    "| `modules.md` | Module structure, file layout | basic-design, detail-design, implement |",
    "| `conventions.md` | Entity/DTO/Mapper/Controller patterns, MapStruct, Records | detail-design, implement |",
    "| `architecture.md` | 4-layer DDD, data flow, AOP, session, Redis | basic-design, detail-design, implement |",
    "| `database.md` | ERD, Liquibase workflow, entity list | detail-design, implement |",
    "| `security.md` | Roles, permissions, auth flow, @AccessControl | implement |",
    "| `api.md` | URL scheme, request/response patterns, error codes | detail-design, implement |",
    "| `testing.md` | JUnit 5 config, Playwright fixtures, test data strategy | testing |",
    "",
    "All phases read `.vibeflow/PROJECT_CONTEXT.md` (core ~150 lines) first.",
    "",
    "Generated by VibeFlow. Content populated by `vf init --ai` enrichment.",
  ].join("\n");
  writeFileSync(join(ctxDir, "README.md"), readmeContent);
  written.push(`${CTX_DIR}/context/README.md`);

  for (const topic of topics) {
    const topicPath = join(ctxDir, `${topic}.md`);
    const placeholder = [
      `# ${topic}`,
      "",
      "Context populated by `vf init --ai` enrichment.",
      "",
      `This file covers ${topic} topics relevant to the project.`,
      "",
      "---",
      "",
      "Generated by VibeFlow.",
    ].join("\n");
    writeFileSync(topicPath, placeholder);
    written.push(`${CTX_DIR}/context/${topic}.md`);
  }

  return written;
}

/** Copy phase skill templates for phases where the user did NOT provide
 * input/output paths. Writes to `.vibeflow/skills/<phase>/SKILL.md`.
 * For phases WITH in/out paths, call `renderPhaseSkillToCanonical` instead. */

export function copyPhaseSkillTemplates(
  base: string,
  phases: WorkflowPhase[],
  projectName: string,
  inject: { onWarn?: (msg: string) => void } = {},
): string[] {
  const onWarn = inject.onWarn ?? ((msg: string) => console.warn(msg));
  const written: string[] = [];
  const VF_VERSION = VERSION;

  for (const phase of phases) {
    const slug = phaseSlug(phase);
    const canonDir = join(base, CTX_DIR, "skills", slug);
    const canonPath = join(canonDir, "SKILL.md");
    const hasPaths = Boolean(phase.inputs?.length) || Boolean(phase.outputs?.length);

    if (hasPaths) {
      // User provided in/out — use template-based render with Example
      mkdirSync(canonDir, { recursive: true });
      const body = renderPhaseSkillToCanonical(phase, projectName, VF_VERSION);
      writeFileSync(canonPath, body);
    } else {
      // No in/out — copy canonical template
      const template = readPhaseSkillTemplate(phase);
      if (!template) {
        onWarn(`vibeflow: template not found for phase "${phase.name}" (${slug}) — skipping`);
        continue;
      }
      mkdirSync(canonDir, { recursive: true });
      const body = template
        .replace(/\{\{PROJECT_NAME\}\}/g, projectName)
        .replace(/\{\{VERSION\}\}/g, VF_VERSION)
        .replace(/^status: template$/m, "status: template")
        .replace(/\{\{phase\.inputs path\}\}/g, "_not provided_")
        .replace(/\{\{phase\.outputs path\}\}/g, "_not provided_")
        .replace(/\{\{template if provided\}\}/g, phase.template ?? "_not provided_");
      writeFileSync(canonPath, body);
    }

    // Create references/ scaffolding — copy pre-existing reference files
    // from the package template (e.g. viewpoint_testing.md, template stubs).
    // If none exist, create empty README placeholders.
    const refDir = join(canonDir, "references");
    copyPhaseTemplateReferences(slug, refDir);
    written.push(`.vibeflow/skills/${slug}/references/`);
  }

  return written;
}

export { renderPhaseSkillToCanonical, copyPhaseTemplateReferences };
