import { existsSync, readFileSync, writeFileSync } from "node:fs";
import type { AgentEngine } from "../agents/render.js";
import { agentFilePath } from "../agents/render.js";
import type { RoleModel, RoleSpec, ToolIntent } from "../agents/role.js";
import type { WorkflowPhase } from "../ai-init-workflow.js";
import { VERSION } from "../core.js";
import { VF_BLOCK_END, VF_BLOCK_START, mergeManagedBlock } from "../workflow/merge.js";
import { skillFilePath } from "./common-template.js";
import { phaseSlug } from "./types.js";

// ── Phase helpers ──────────────────────────────────────────────────────────

export function phaseAgentName(phase: WorkflowPhase): string {
  return `phase-${phaseSlug(phase)}`;
}

export function orchestratorAgentName(): string {
  return "workflow-orchestrator";
}

export function orchestratorAgentPath(engine: AgentEngine): string {
  return agentFilePath(engine, orchestratorAgentName());
}

// ── Orchestrator definition ────────────────────────────────────────────────

function renderAgentPaths(phase: WorkflowPhase, engines: AgentEngine[]): string {
  const slug = phaseSlug(phase);
  const first = engines[0];
  if (engines.length === 1 && first) {
    return `- Agent: \`${agentFilePath(first, `phase-${slug}`)}\``;
  }
  return engines.map((e) => `- Agent (${e}): \`${agentFilePath(e, `phase-${slug}`)}\``).join("\n");
}

function renderSkillPaths(phase: WorkflowPhase, engines: AgentEngine[]): string {
  const slug = phaseSlug(phase);
  const first = engines[0];
  if (engines.length === 1 && first) {
    return `- Skill: \`${skillFilePath(first, slug)}\``;
  }
  return engines.map((e) => `- Skill (${e}): \`${skillFilePath(e, slug)}\``).join("\n");
}

function renderWorkflowBody(
  phases: WorkflowPhase[],
  engines: AgentEngine[],
  projectName: string,
): string {
  const lines: string[] = [
    `# Workflow Orchestrator — ${projectName}`,
    "",
    `Generated by VibeFlow v${VERSION}. Edit phase descriptions and DoDs here; re-run \`vf init\` to regenerate agent/skill files.`,
    "",
    "## How dispatch works",
    "",
    "Each phase's inputs/outputs are NOT hardcoded in this file. They are resolved at dispatch time from `WORKFLOW_STATE.json` (per-phase `work_units[].scope`). The phase skill's `{{INPUT_PATH}}`/`{{OUTPUT_PATH}}` placeholders are filled from those values. Edit `WORKFLOW_STATE.json` to retarget a phase without regenerating agents.",
    "",
    "## Phases",
    "",
    `Total: ${phases.length} phase(s)`,
    "",
  ];
  for (const [i, p] of phases.entries()) {
    const prev = i > 0 ? phases[i - 1] : undefined;
    const prevName = prev?.name ?? null;
    const deps = prevName ? `Depends on: ${prevName}` : "No dependencies";
    const hasPaths = Boolean(p.inputs?.length) || Boolean(p.outputs?.length);
    const entries: Array<string | null> = [
      `### ${i + 1}. ${p.name}`,
      "",
      `- Description: ${p.description || "(none)"}`,
      renderAgentPaths(p, engines),
      renderSkillPaths(p, engines),
      `- ${deps}`,
      "- Inputs/Outputs: resolved at dispatch from WORKFLOW_STATE.json (see `work_units[].scope`)",
      hasPaths
        ? `- Original paths from init: ${[p.inputs ?? [], p.outputs ?? []].flat().filter(Boolean).join(", ")}`
        : null,
      p.template ? `- Template: ${p.template}` : null,
      p.dod ? `- Definition of Done: ${p.dod}` : null,
      "",
    ];
    lines.push(...entries.filter((e): e is string => e !== null));
  }
  lines.push(
    "## Usage",
    "",
    "Run `vf orchestrate` to execute pending phases in order.",
    "Each phase is dispatched to its configured agent with the associated skill.",
    "Inputs/outputs are taken from WORKFLOW_STATE.json at dispatch time, not hardcoded in the agent file.",
    "",
  );
  return lines.filter((l) => l !== null).join("\n");
}

export function buildOrchestratorSpec(
  phases: WorkflowPhase[],
  engines: AgentEngine[],
  projectName: string,
): RoleSpec {
  return {
    name: orchestratorAgentName(),
    description: `Coordinate ${projectName} workflow phases and dispatch phase agents in order`,
    body: renderWorkflowBody(phases, engines, projectName),
    tools: ["read", "write", "edit", "bash", "grep", "glob"],
    model: "sonnet" as RoleModel,
  };
}

// ── Per-phase agent files ──────────────────────────────────────────────────

function inferPhaseTools(_phase: WorkflowPhase): ToolIntent[] {
  return ["read", "write", "edit", "bash", "grep", "glob"];
}

export function buildPhaseSpec(
  phase: WorkflowPhase,
  projectName: string,
  skillPath: string,
): RoleSpec {
  const hasPaths = Boolean(phase.inputs?.length) || Boolean(phase.outputs?.length);
  const body = [
    `# ${phase.name}`,
    "",
    phase.description || `Execute the ${phase.name} phase.`,
    "",
    "## Inputs",
    "",
    "Resolved at dispatch time from `WORKFLOW_STATE.json` → `work_units[name=<phase>].scope`.",
    "The skill file defines the transformation and uses `{{INPUT_PATH}}`/`{{OUTPUT_PATH}}` as placeholders",
    "that are filled from the work unit's scope at dispatch.",
    "",
    hasPaths
      ? `_Original paths from questionnaire: ${[phase.inputs ?? [], phase.outputs ?? []].flat().filter(Boolean).join(", ")}_`
      : "_No concrete paths provided during init._",
    "",
    "## Skill",
    "",
    `Read \`${skillPath}\` before executing this phase.`,
    "",
  ].join("\n");
  return {
    name: phaseAgentName(phase),
    description: phase.description || `Execute ${phase.name} phase`,
    body,
    tools: inferPhaseTools(phase),
    model: "sonnet" as RoleModel,
  };
}

// ── Engine instruction managed block update ────────────────────────────────

export function orchestratorSnippet(
  phases: WorkflowPhase[],
  engines: AgentEngine[],
): string | null {
  if (!phases.length) return null;
  const files = engines.map((e) => `\`${orchestratorAgentPath(e)}\``).join(", ");
  return [
    "## Workflow",
    "",
    `This project has ${phases.length} defined workflow phase(s).`,
    `Read ${files} for the phase DAG and agent assignments.`,
    "Run `vf orchestrate` to execute pending phases.",
    "",
  ].join("\n");
}

export function appendToManagedBlock(filePath: string, addendum: string): void {
  if (!existsSync(filePath)) return;
  const content = readFileSync(filePath, "utf8");
  const start = content.indexOf(VF_BLOCK_START);
  const end = content.indexOf(VF_BLOCK_END);
  let newBlock: string;
  if (start !== -1 && end !== -1 && end > start) {
    const current = content.slice(start + VF_BLOCK_START.length, end).trim();
    newBlock = `${current}\n\n${addendum}`;
  } else {
    newBlock = addendum;
  }
  const merged = mergeManagedBlock(content, newBlock);
  writeFileSync(filePath, merged.content);
}

// ── Enrichment prompt helpers ──────────────────────────────────────────────

export function renderPhaseListLine(phase: WorkflowPhase, engines: AgentEngine[]): string {
  const slug = phaseSlug(phase);
  const dod = phase.dod ? `DoD: ${phase.dod}` : "";
  const agentPaths = engines.map((e) => agentFilePath(e, `phase-${slug}`));
  const agents = agentPaths.join(", ");
  const skillPaths = engines.map((e) => skillFilePath(e, slug)).join(", ");
  return `  - ${phase.name} (agent: ${agents}, skill: ${skillPaths}) ${dod}`;
}
