import { existsSync, readFileSync, rmSync } from "node:fs";
import { join, resolve } from "node:path";
import {
  CTX_DIR,
  type WorkUnit,
  type WorkflowState,
  readState,
  recomputeTotals,
  writeState,
} from "../core.js";
import { findScopeConflicts } from "../gates.js";

/** Injected filesystem seams so tests never touch the real disk destructively. */
export type RmOp = (path: string) => void;
export type ExistsOp = (path: string) => boolean;

const defaultRm: RmOp = (p) => rmSync(p, { recursive: true, force: true });
const defaultExists: ExistsOp = (p) => existsSync(p);

/** Engine files VibeFlow generates; preserved on a default delete, only removed by --all + marker. */
const MANAGED_ENGINE_FILES = [
  "CLAUDE.md",
  "AGENTS.md",
  ".github/copilot-instructions.md",
  ".mcp.json",
  ".codex/config.toml",
];

/** A directory that must NEVER be deleted by any plan. */
const GIT_DIR = ".git";

/** Marker strings the adapters embed in every file VibeFlow owns (adapters.ts engineBody/headers). */
const GENERATION_MARKERS = ["generated by vibeflow", "managed by vibeflow"];

/** True when file content still carries a VibeFlow generation/management marker (case-insensitive). */
export function isManagedGenerated(content: string): boolean {
  const lower = content.toLowerCase();
  return GENERATION_MARKERS.some((m) => lower.includes(m));
}

export interface DeletePlan {
  repo: string;
  ctxDir: string;
  targets: string[];
  preserved: string[];
  summary: string;
}

/** Build the human summary of the workflow being deleted, so the caller shows EXACTLY what goes. */
function describeWorkflow(repo: string, state: WorkflowState | null): string {
  if (!state) return `no workflow in ${repo}`;
  const names = state.work_units.map((u) => u.name);
  const unitLine = names.length
    ? `${names.length} work unit(s): ${names.join(", ")}`
    : "0 work units";
  return `workflow in ${repo}\n  goal: ${state.goal}\n  ${unitLine}`;
}

/** Classify each managed engine file under --all: targeted when still generated, preserved when edited. */
function classifyManagedFiles(
  repo: string,
  exists: ExistsOp,
): { targets: string[]; notes: string[] } {
  const targets: string[] = [];
  const notes: string[] = [];
  for (const rel of MANAGED_ENGINE_FILES) {
    const abs = join(repo, rel);
    if (!exists(abs)) continue;
    try {
      if (isManagedGenerated(readFileSync(abs, "utf8"))) {
        targets.push(abs);
      } else {
        notes.push(rel);
      }
    } catch (e) {
      // ENOENT means the file was deleted between the exists() check and readFileSync — skip.
      // Anything else (EACCES, EISDIR) is unexpected; fall through to preserve conservatively.
      if ((e as NodeJS.ErrnoException)?.code === "ENOENT") continue;
      notes.push(rel);
    }
  }
  return { targets, notes };
}

/**
 * Plan deleting a SPECIFIC workflow in `base`. Default scope removes only `.vibeflow/` and
 * preserves the (possibly hand-edited) engine files. `--all` additionally targets managed
 * engine files, but ONLY those still carrying a generation marker; edited ones are preserved
 * and noted. `.git` is never a target. The summary shows the resolved goal + unit names so the
 * caller can confirm the right workflow before anything is removed.
 */
export function planDelete(
  base: string,
  opts: { all?: boolean } = {},
  exists: ExistsOp = defaultExists,
): DeletePlan {
  const repo = resolve(base);
  const ctxDir = join(repo, CTX_DIR);
  const state = readState(repo);
  if (!exists(ctxDir)) {
    return { repo, ctxDir, targets: [], preserved: [], summary: `no workflow in ${repo}` };
  }
  const targets = [ctxDir];
  const preserved: string[] = [];
  let summary = describeWorkflow(repo, state);
  if (!opts.all) {
    for (const rel of MANAGED_ENGINE_FILES) {
      if (exists(join(repo, rel))) preserved.push(join(repo, rel));
    }
    return { repo, ctxDir, targets, preserved, summary };
  }
  const { targets: managed, notes } = classifyManagedFiles(repo, exists);
  targets.push(...managed);
  for (const rel of notes) preserved.push(join(repo, rel));
  if (notes.length) summary += `\n  preserved (hand-edited): ${notes.join(", ")}`;
  return { repo, ctxDir, targets, preserved, summary };
}

/**
 * Execute a delete plan via the injected `rm`. Guard: only removes paths in `plan.targets`, and
 * never `.git`. Returns the list of removed paths.
 */
export function applyDelete(plan: DeletePlan, rm: RmOp = defaultRm): string[] {
  const removed: string[] = [];
  for (const target of plan.targets) {
    if (target.endsWith(GIT_DIR) || target.includes(`${GIT_DIR}/`)) continue; // never .git
    rm(target);
    removed.push(target);
  }
  return removed;
}

/**
 * Delete a single work UNIT by name from the workflow at `base` (mirrors commands.ts mutateUnits
 * delete). Recomputes totals and persists. Returns the updated state, or null when the workflow
 * or the named unit is not found (so the caller can list available names).
 */
export function deleteUnit(base: string, name: string): WorkflowState | null {
  const repo = resolve(base);
  const state = readState(repo);
  if (!state) return null;
  const target = name.trim();
  if (!target || target.includes("..") || target.includes("/")) return null;
  const idx = state.work_units.findIndex((u) => u.name === target);
  if (idx === -1) return null;
  state.work_units.splice(idx, 1);
  recomputeTotals(state);
  writeState(repo, state);
  const unitDir = join(repo, CTX_DIR, "workunits", target);
  if (existsSync(unitDir)) rmSync(unitDir, { recursive: true, force: true });
  return state;
}

/** A work unit may carry an import breadcrumb (optional, round-trips through JSON). */
export type ImportedUnit = WorkUnit & { imported_from?: string };

export type CollisionPolicy = "skip" | "rename" | "replace";

export interface MergeOpts {
  onNameCollision: CollisionPolicy;
  srcLabel: string;
}

export interface ScopeConflict {
  unit: string;
  kind: "scope-overlap";
  detail: string;
}

export interface MergeResult {
  merged: WorkflowState;
  added: string[];
  renamed: [string, string][];
  conflicts: ScopeConflict[];
  goalReconciliation: string;
}

/**
 * Reset an imported unit so it carries no false proof: status pending, confidence 0, no evidence
 * (the evidence paths point at the SOURCE repo and would violate the confidence/evidence gate).
 * Records an `imported_from` breadcrumb.
 */
function resetImported(unit: WorkUnit, srcLabel: string): ImportedUnit {
  return {
    ...unit,
    status: "pending",
    confidence: 0,
    evidence: [],
    gates: { build: "pending", lint: "pending", test: "pending", review: "pending" },
    imported_from: srcLabel,
  };
}

/** Append src goal + success criteria into dest's criteria, de-duped, preserving dest order. */
function reconcileCriteria(dest: WorkflowState, src: WorkflowState): string[] {
  const merged = [...dest.success_criteria, ...src.success_criteria, src.goal];
  return [...new Set(merged.filter((s) => s.trim().length > 0))];
}

/** Insert one source unit under the collision policy, mutating `units` and tracking the outcome. */
function placeUnit(
  units: ImportedUnit[],
  src: WorkUnit,
  opts: MergeOpts,
  out: { added: string[]; renamed: [string, string][] },
): void {
  const idx = units.findIndex((u) => u.name === src.name);
  if (idx === -1) {
    units.push(resetImported(src, opts.srcLabel));
    out.added.push(src.name);
    return;
  }
  if (opts.onNameCollision === "skip") return;
  if (opts.onNameCollision === "replace") {
    units[idx] = resetImported(src, opts.srcLabel);
    out.added.push(src.name);
    return;
  }
  const newName = `${src.name}:${opts.srcLabel}`;
  units.push(resetImported({ ...src, name: newName }, opts.srcLabel));
  out.renamed.push([src.name, newName]);
  out.added.push(newName);
}

/**
 * Merge a source workflow's work units into a copy of `dest`. De-dups by name under the chosen
 * collision policy ("rename" suffixes `:<srcLabel>"`, "skip" keeps dest, "replace" takes src).
 * Imported units are RESET (pending / confidence 0 / no evidence) so importing never fabricates
 * confidence=1 proof. Surfaces — but never auto-resolves — scope overlaps, reconciles the goal,
 * and recomputes totals. Pure: does not write.
 */
export function mergeStates(dest: WorkflowState, src: WorkflowState, opts: MergeOpts): MergeResult {
  const units: ImportedUnit[] = dest.work_units.map((u) => ({ ...u }));
  const out: { added: string[]; renamed: [string, string][] } = { added: [], renamed: [] };
  for (const unit of src.work_units) placeUnit(units, unit, opts, out);

  const conflicts: ScopeConflict[] = findScopeConflicts(units).map(([a, b]) => ({
    unit: a,
    kind: "scope-overlap" as const,
    detail: `"${a}" and "${b}" declare overlapping scopes`,
  }));

  const merged = recomputeTotals({
    ...dest,
    work_units: units,
    success_criteria: reconcileCriteria(dest, src),
  });
  const goalReconciliation = `kept dest goal "${dest.goal}"; folded src goal "${src.goal}" into success criteria`;
  return { merged, added: out.added, renamed: out.renamed, conflicts, goalReconciliation };
}

/**
 * Read the destination workflow at `destBase` and the source at `srcPath`, then merge them.
 * Returns null when either workflow is missing. Dry by default — the caller persists the merged
 * state (e.g. on `--yes`); this never writes.
 */
export function importWorkflow(
  destBase: string,
  srcPath: string,
  opts: { onNameCollision: CollisionPolicy; srcLabel?: string },
): MergeResult | null {
  const dest = readState(destBase);
  const src = readState(resolve(srcPath));
  if (!dest || !src) return null;
  const srcLabel = opts.srcLabel?.trim() || resolve(srcPath);
  return mergeStates(dest, src, { onNameCollision: opts.onNameCollision, srcLabel });
}
