import { spawnSync } from "node:child_process";
import { basename } from "node:path";
import { type Engine, cwd } from "./core.js";

export interface ProjectContext {
  name: string;
  goal: string;
  summary: string;
  docSource?: string;
  taskSource?: string;
  fileTypes?: string[];
  expectedResult?: string;
  sample?: string;
}

export function defaultContext(): ProjectContext {
  return {
    name: basename(cwd()),
    goal: "Describe the task in vibeflow/TASK_CONTEXT.md before dispatching an engine.",
    summary:
      "Project context is generated by VibeFlow. Edit vibeflow/PROJECT_CONTEXT.md to refine it.",
  };
}

/**
 * AI bridge. Per the VibeFlow principle, generated files are composed by an AI from
 * canonical context rather than copied from static templates. When the VIBEFLOW_AI
 * environment variable points to a command, the prompt is piped to it and its stdout is
 * used verbatim. Otherwise VibeFlow falls back to a deterministic projection of the
 * canonical context so the tool remains usable offline.
 */
export function aiGenerate(prompt: string, fallback: () => string): string {
  const cmd = process.env.VIBEFLOW_AI;
  if (!cmd) return fallback();
  const r = spawnSync(cmd, { input: prompt, shell: true, encoding: "utf8" });
  if (r.status === 0 && r.stdout.trim()) return r.stdout;
  return fallback();
}

// --- Canonical context files (the single source of truth) ---
export function canonicalFiles(ctx: ProjectContext): Record<string, string> {
  const sources = [
    `- Documentation source: ${ctx.docSource ?? "TODO"}`,
    `- Task/issue source: ${ctx.taskSource ?? "TODO"}`,
    ctx.fileTypes?.length ? `- File types in scope: ${ctx.fileTypes.join(", ")}` : null,
  ]
    .filter(Boolean)
    .join("\n");
  const requirements = ctx.expectedResult
    ? `- Expected result: ${ctx.expectedResult}\n`
    : "- TODO: capture business and technical requirements.\n";
  const sample = ctx.sample ? `- Reference/sample: ${ctx.sample}\n` : "";
  return {
    "vibeflow/PROJECT_CONTEXT.md": `# Project Context\n\n- Name: ${ctx.name}\n- Summary: ${ctx.summary}\n${sources}\n`,
    "vibeflow/REQUIREMENTS.md": `# Requirements\n\n${requirements}${sample}`,
    "vibeflow/TASK_CONTEXT.md": `# Task Context\n\n- Goal: ${ctx.goal}\n- Definition of Done: ${ctx.expectedResult ?? "TODO"}\n- Must not change: TODO\n`,
    "vibeflow/WORKFLOW_POLICY.md":
      "# Workflow Policy\n\n- No evidence, no conclusion. No verification, no completion.\n- Generate the fewest files possible; every generated file is AI-composed from this context.\n- Ask approval only for side effects or high-risk actions.\n",
    "vibeflow/SKILL_INDEX.md":
      "# Skill Index\n\n| skill | status | capabilities |\n|-------|--------|--------------|\n",
  };
}

// --- Per-engine adapter output, AI-composed from canonical context ---
function engineBody(engine: Engine, ctx: ProjectContext): string {
  const shared = `Project: ${ctx.name}\nGoal: ${ctx.goal}\n\nPolicy:\n- Use verified skills when a task matches one; do not invent manual steps.\n- Back every factual claim with a file path, command output, or test result.\n- No verification, no completion.\n`;
  if (engine === "claude") {
    return `# CLAUDE.md\n\n${shared}\nThis file is generated by VibeFlow from vibeflow/*. Do not edit by hand; re-run \`vf init\`.\n`;
  }
  return `# AGENTS.md\n\n${shared}\nGenerated by VibeFlow from vibeflow/*. Re-run \`vf init\` to regenerate.\n`;
}

export function engineFiles(
  engine: Engine,
  ctx: ProjectContext,
  useAi = true,
): Record<string, string> {
  const compose = (prompt: string, fallback: () => string): string =>
    useAi ? aiGenerate(prompt, fallback) : fallback();
  const prompt = `Compose the ${engine} instruction file for project "${ctx.name}" from this context:\n${JSON.stringify(ctx)}`;
  const body = compose(prompt, () => engineBody(engine, ctx));
  switch (engine) {
    case "claude":
      return { "CLAUDE.md": body };
    case "codex":
      return { "AGENTS.md": body };
    case "copilot":
      return {
        "AGENTS.md": body,
        ".github/copilot-instructions.md": compose(
          `Compose .github/copilot-instructions.md for "${ctx.name}".`,
          () =>
            `# Copilot Instructions\n\n${engineBody("copilot", ctx)}\nPath-specific rules live in .github/instructions/*.instructions.md.\n`,
        ),
      };
  }
}

export function dispatchPrompt(engine: Engine, ctx: ProjectContext, units: string[]): string {
  return [
    `# VibeFlow dispatch → ${engine}`,
    "",
    `Goal: ${ctx.goal}`,
    `Work units: ${units.length ? units.join(", ") : "(none — running the whole task)"}`,
    "",
    "Constraints:",
    "- Stay within the declared scope of your work unit.",
    "- Use selected skills; do not invent manual steps when a verified skill exists.",
    "- Return a JSON summary: skills used, files changed, commands run, tests run, confidence, uncertainty.",
    "",
  ].join("\n");
}
